volumes:
  libraries:
  logs:
  mods:
  versions:
services:
  java:
    container_name: java
    build: .
    ports:
      - "25565:25565"
      - "25565:25565/udp"
      - "19132:19132"
      - "19132:19132/udp"
    volumes:
      - './data:/minecraft_data'
