config-version = "2.7"
bind = "0.0.0.0:25577"
motd = "WSL Verification Proxy"
show-max-players = 100
online-mode = true
force-key-authentication = true
player-info-forwarding-mode = "modern"
forwarding-secret-file = "forwarding.secret"
announce-forge = false
kick-existing-players = false
ping-passthrough = "disabled"
enable-player-address-logging = true

[servers]
lobby = "lobby:25565"
survival = "survival:25565"

try = [
  "lobby",
]

[forced-hosts]
"lobby.local" = [
  "lobby",
]
