#:schema ../config.schema.json
name = "resource"
display_name = "資源採集"
display_color = "aqua"
world_type = "normal"
deletable = true

[dimensions.nether]

[dimensions.end]

[mv_set]
gamemode = "survival"
pvp = "true"
difficulty = "hard"
