services:
  world:
    image: itzg/minecraft-server:java21
    container_name: mc-world
    restart: unless-stopped
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: PAPER
      VERSION: "1.21.11"
      LEVEL: "mainhall"
      LEVEL_TYPE: "FLAT"
      MEMORY: "4G"
      SERVER_NAME: "mainhall"
      MOTD: "Main Server"
      ONLINE_MODE: "TRUE"
      ENABLE_RCON: "FALSE"
      CREATE_CONSOLE_IN_PIPE: "true"
      HANGAR_PROJECTS: "LuckPerms"
      MODRINTH_PROJECTS: "multiverse-core,multiverse-portals"
    volumes:
      - ./runtime/world:/data
    networks:
      - mcnet

networks:
  mcnet:
    driver: bridge
