services:
  lobby:
    image: itzg/minecraft-server:java21
    container_name: mc-lobby
    restart: unless-stopped
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: PAPER
      VERSION: "1.21.11"
      MEMORY: "4G"
      SERVER_NAME: "main"
      MOTD: "Main Server"
      ONLINE_MODE: "TRUE"
      ENABLE_RCON: "FALSE"
      CREATE_CONSOLE_IN_PIPE: "true"
      SPIGET_RESOURCES: "28140" # LuckPerms
    volumes:
      - ./runtime/lobby:/data
    networks:
      - mcnet

networks:
  mcnet:
    driver: bridge
